// Seed data for dev/demo — run once via /api/seed
export const SEED_PROPERTIES = [
  {
    address: "רחוב דיזנגוף 72",
    city: "תל אביב",
    landlord_name: "דוד כהן",
    lat: 32.0805,
    lng: 34.7742,
  },
  {
    address: "רחוב בן יהודה 18",
    city: "ירושלים",
    landlord_name: "משה לוי",
    lat: 31.7853,
    lng: 35.2141,
  },
  {
    address: "שדרות הנשיא 45",
    city: "חיפה",
    landlord_name: "רחל אברהם",
    lat: 32.8192,
    lng: 34.9993,
  },
];

export const SEED_REVIEWS = [
  // Tel Aviv property (index 0) — 4 reviews
  {
    propIdx: 0,
    rating: 5,
    rating_maintenance: 5,
    rating_communication: 5,
    rating_neighbors: 4,
    rating_value: 4,
    text: "משכיר מעולה, תמיד זמין ומתקן כל תקלה תוך יום. הדירה במצב מצוין ושכנים שקטים.",
    is_anonymous: false,
    tags: ["תחזוקה טובה", "משכיר נחמד", "מגיב מהר"],
  },
  {
    propIdx: 0,
    rating: 4,
    rating_maintenance: 4,
    rating_communication: 3,
    rating_neighbors: 4,
    rating_value: 3,
    text: "בסך הכל מרוצה, לפעמים לוקח לו זמן לענות אבל בסוף מסתדר.",
    is_anonymous: true,
    tags: ["מגיב לאט", "תחזוקה טובה"],
  },
  {
    propIdx: 0,
    rating: 2,
    rating_maintenance: 2,
    rating_communication: 1,
    rating_neighbors: 3,
    rating_value: 2,
    text: "הפיקדון לא הוחזר אחרי 3 חודשים מהיציאה. צריך להתחיל בהליכים משפטיים.",
    is_anonymous: true,
    tags: ["פיקדון לא הוחזר", "לא מתקן תקלות"],
  },
  {
    propIdx: 0,
    rating: 3,
    rating_maintenance: 3,
    rating_communication: 4,
    rating_neighbors: 2,
    rating_value: 3,
    text: "השכן מעל רועש מאוד בלילה, המשכיר לא עשה כלום עם זה.",
    is_anonymous: true,
    tags: ["שכן רועש", "מגיב מהר"],
  },
  // Jerusalem property (index 1) — 3 reviews
  {
    propIdx: 1,
    rating: 1,
    rating_maintenance: 1,
    rating_communication: 1,
    rating_neighbors: 3,
    rating_value: 2,
    text: "נכנס לדירה ללא תיאום מראש פעמיים. הרגשתי שפרטיותי מופרת לחלוטין.",
    is_anonymous: true,
    tags: ["חדירת פרטיות", "לא מתקן תקלות"],
  },
  {
    propIdx: 1,
    rating: 4,
    rating_maintenance: 4,
    rating_communication: 5,
    rating_neighbors: 5,
    rating_value: 4,
    text: "חוויה נהדרת, שכנים נחמדים ומשכיר קשוב. הדירה היתה נקייה ומסודרת.",
    is_anonymous: false,
    tags: ["משכיר נחמד", "מחיר הוגן", "תחזוקה טובה"],
  },
  {
    propIdx: 1,
    rating: 2,
    rating_maintenance: 3,
    rating_communication: 2,
    rating_neighbors: 4,
    rating_value: 1,
    text: "העלה את השכירות ב-20% ללא הודעה מספיקה. קשה להתארגן כך.",
    is_anonymous: true,
    tags: ["העלה שכירות פתאום"],
  },
  // Haifa property (index 2) — 3 reviews
  {
    propIdx: 2,
    rating: 3,
    rating_maintenance: 2,
    rating_communication: 3,
    rating_neighbors: 3,
    rating_value: 4,
    text: "ריח רטיבות בממ\"ד שדווח כמה פעמים ולא טופל. מחיר הוגן לאזור.",
    is_anonymous: true,
    tags: ["ריח רטיבות", "מחיר הוגן"],
  },
  {
    propIdx: 2,
    rating: 5,
    rating_maintenance: 5,
    rating_communication: 5,
    rating_neighbors: 5,
    rating_value: 5,
    text: "הכי טוב שגרתי בו. הכל עובד, המשכירה תמיד זמינה ונחמדה מאוד.",
    is_anonymous: false,
    tags: ["תחזוקה טובה", "משכיר נחמד", "מגיב מהר", "מחיר הוגן"],
  },
  {
    propIdx: 2,
    rating: 3,
    rating_maintenance: 3,
    rating_communication: 2,
    rating_neighbors: 4,
    rating_value: 3,
    text: "בסדר כללי. יש עיכובים בתיקונים קטנים אבל אין בעיות גדולות.",
    is_anonymous: true,
    tags: ["מגיב לאט"],
  },
];
